"""Numba-compiled numerical kernels shared by the laserttm solvers.

These are line-faithful ports of the corresponding MATLAB local functions
(the validation suite in ``tests/`` asserts agreement with golden fixtures
generated by the MATLAB reference implementation). The hand-rolled Thomas
solves and RK4 stepping are kept algorithm-identical on purpose: with the
same step sequence, agreement with MATLAB is limited only by libm/round-off,
not integrator differences.

Set the environment variable ``NUMBA_DISABLE_JIT=1`` to run them as plain
Python for debugging.
"""

from __future__ import annotations

import numpy as np
from numba import njit

# Temporal pulse profile codes (MATLAB used strings; Numba wants ints)
PROFILE_GAUSSIAN = 0
PROFILE_SQUARE = 1
PROFILE_EXP = 2

_PROFILE_CODES = {
    "gaussian": PROFILE_GAUSSIAN,
    "square": PROFILE_SQUARE,
    "exp": PROFILE_EXP,
}


def profile_code(name: str) -> int:
    """Map a pulse-profile name ('gaussian'|'square'|'exp') to its kernel code."""
    try:
        return _PROFILE_CODES[name.lower()]
    except KeyError:
        raise ValueError(
            f"Unknown pulse profile '{name}'. Use 'gaussian', 'square', or 'exp'."
        ) from None


@njit(cache=True)
def pulse_profile(code, t_rel, tau):
    """Normalized temporal pulse profile g(t); integral over all time = 1.

    Port of pulseProfileFunc (MATLAB).
    """
    if code == PROFILE_GAUSSIAN:
        a = 4.0 * np.log(2.0) / (tau * tau)
        return np.sqrt(a / np.pi) * np.exp(-a * t_rel * t_rel)
    elif code == PROFILE_SQUARE:
        if abs(t_rel) <= tau / 2.0:
            return 1.0 / tau
        return 0.0
    elif code == PROFILE_EXP:
        if t_rel >= 0.0:
            return (1.0 / tau) * np.exp(-t_rel / tau)
        return 0.0
    return 0.0


@njit(cache=True)
def source_temporal(t, n_pulses, trep, pulse_offset, code, tau):
    """Sum of normalized temporal pulse profiles at time t (unitless, 1/s).

    Port of sourceTemporalPulses / the temporal part of sourceFunc (MATLAB).
    O(1) per call: only pulses within 10*tau of t contribute (the source is
    identically zero beyond that cutoff — the property that lets Phase 1
    integration relax its step cap after each pulse).
    """
    cutoff = 10.0 * tau
    t_shift = t - pulse_offset
    # MATLAB round(): half away from zero. Differences vs floor(x+0.5) only
    # occur exactly halfway between pulses, where the cutoff zeroes g anyway.
    n_nearest = int(np.floor(t_shift / trep + 0.5))
    n_lo = max(0, n_nearest - 1)
    n_hi = min(n_pulses - 1, n_nearest + 1)
    g_sum = 0.0
    for n in range(n_lo, n_hi + 1):
        t_rel = t_shift - n * trep
        if abs(t_rel) <= cutoff:
            g_sum += pulse_profile(code, t_rel, tau)
    return g_sum


@njit(cache=True)
def _ttm_derivs_0d(t, te, tl, gamma, g_ep, cl,
                   n_pulses, trep, pulse_offset, code, tau, eabs_vol):
    """Port of ttmDerivatives (Surface_Point_Solver.m): 0D coupled TTM RHS."""
    ce = max(gamma * max(te, 1.0), 1e-9)
    s = eabs_vol * source_temporal(t, n_pulses, trep, pulse_offset, code, tau)
    d_te = (-g_ep * (te - tl) + s) / ce
    d_tl = (g_ep * (te - tl)) / cl
    return d_te, d_tl, s


@njit(cache=True)
def rk4_pulse_phase(t_pulse, t_start, te0, tl0,
                    gamma, g_ep, cl,
                    n_pulses, trep, pulse_offset, code, tau, eabs_vol,
                    pulse_fine_win, relax_tol, relax_max_t, dt_floor):
    """Phase 1 of the 0D two-stage model: adaptive RK4 around one pulse.

    Line-faithful port of the Phase 1 while-loop in Surface_Point_Solver.m:
    stability-limited dt (0.2*Ce/G) with fine resolution (tau/40) inside
    +/- pulse_fine_win of the pulse center; integrates until |Te-Tl|/Tl
    converges below relax_tol or relax_max_t past the pulse center.

    Returns (times, Te, Tl, absorbed) where absorbed is the trapezoidal
    integral of the volumetric source over the phase [J/m^3].
    """
    # Typical phases take a few hundred steps; the grow-by-buf path below
    # handles the rare longer relaxation. (MATLAB used a 100000 block, which
    # cost three 800 KB allocations per pulse for nothing.)
    buf = 4096
    loc_t = np.empty(buf)
    loc_te = np.empty(buf)
    loc_tl = np.empty(buf)
    loc_t[0] = t_start
    loc_te[0] = te0
    loc_tl[0] = tl0
    k = 0  # index of last filled entry (0-based)
    absorbed = 0.0
    past_pulse = False

    while True:
        te_n = loc_te[k]
        tl_n = loc_tl[k]
        tc = loc_t[k]

        # --- adaptive dt (stability-limited near coupling) ---
        dist_p = abs(tc - t_pulse)
        ce_now = gamma * max(te_n, 1.0)
        dt_stab = 0.2 * ce_now / g_ep       # RK4 stability limit
        dt_pulse = tau / 40.0               # resolution within pulse
        if dist_p < pulse_fine_win:
            dt = min(dt_stab, dt_pulse)     # fine resolution, stable
        else:
            dt = dt_stab                    # stability-governed
            past_pulse = True
        dt = max(dt, dt_floor)                   # absolute safety floor

        # --- RK4 step ---
        k1e, k1l, s0 = _ttm_derivs_0d(tc, te_n, tl_n,
                                      gamma, g_ep, cl,
                                      n_pulses, trep, pulse_offset, code, tau, eabs_vol)
        k2e, k2l, _ = _ttm_derivs_0d(tc + dt / 2, te_n + dt / 2 * k1e, tl_n + dt / 2 * k1l,
                                     gamma, g_ep, cl,
                                     n_pulses, trep, pulse_offset, code, tau, eabs_vol)
        k3e, k3l, _ = _ttm_derivs_0d(tc + dt / 2, te_n + dt / 2 * k2e, tl_n + dt / 2 * k2l,
                                     gamma, g_ep, cl,
                                     n_pulses, trep, pulse_offset, code, tau, eabs_vol)
        k4e, k4l, s1 = _ttm_derivs_0d(tc + dt, te_n + dt * k3e, tl_n + dt * k3l,
                                      gamma, g_ep, cl,
                                      n_pulses, trep, pulse_offset, code, tau, eabs_vol)

        te_next = max(te_n + (dt / 6.0) * (k1e + 2.0 * k2e + 2.0 * k3e + k4e), 1.0)
        tl_next = max(tl_n + (dt / 6.0) * (k1l + 2.0 * k2l + 2.0 * k3l + k4l), 1.0)
        absorbed += 0.5 * (s0 + s1) * dt

        k += 1
        if k >= loc_t.size:
            # grow buffers (MATLAB grew by bufSz blocks)
            new_t = np.empty(loc_t.size + buf)
            new_te = np.empty(loc_t.size + buf)
            new_tl = np.empty(loc_t.size + buf)
            new_t[: loc_t.size] = loc_t
            new_te[: loc_t.size] = loc_te
            new_tl[: loc_t.size] = loc_tl
            loc_t = new_t
            loc_te = new_te
            loc_tl = new_tl
        loc_t[k] = tc + dt
        loc_te[k] = te_next
        loc_tl[k] = tl_next

        # --- converged? ---
        if past_pulse:
            rel_diff = abs(te_next - tl_next) / max(tl_next, 1.0)
            if rel_diff < relax_tol:
                break
            if (tc + dt - t_pulse) > relax_max_t:
                break

    return loc_t[: k + 1].copy(), loc_te[: k + 1].copy(), loc_tl[: k + 1].copy(), absorbed


# Tungsten hybrid k(T) table (kHybrid_W in the MATLAB solvers): piecewise
# linear in T with flat extrapolation beyond the table boundaries.
KHYBRID_W_T = np.array([293.0, 300.0, 400.0, 600.0, 800.0, 1000.0,
                        1200.0, 1500.0, 2000.0, 2500.0])
KHYBRID_W_K = np.array([174.9, 174.0, 159.0, 137.0, 125.0, 118.0,
                        113.0, 107.0, 100.0, 95.0])


def k_table_for(material: str, ke0: float, kl: float):
    """Return the (T, k) table implementing kHybridFunc for a material.

    Tungsten gets the measured k(T) table; every other material falls back
    to a constant ke0 + kl (as in the MATLAB depth/radial solvers). The
    constant case is encoded as a flat two-point table so a single jitted
    interpolation path serves both.
    """
    if material.lower() == "w":
        return KHYBRID_W_T.copy(), KHYBRID_W_K.copy()
    k_total = ke0 + kl
    return np.array([1.0, 1e12]), np.array([k_total, k_total])


@njit(cache=True)
def k_hybrid(t_arr, k_tab_t, k_tab_k):
    """Piecewise-linear k(T) with flat extrapolation (kHybrid_W semantics)."""
    t_clipped = np.minimum(np.maximum(t_arr, k_tab_t[0]), k_tab_t[-1])
    return np.interp(t_clipped, k_tab_t, k_tab_k)


@njit(cache=True)
def crank_nicolson_step_kt(t_arr, dt, dz, tamb, cl, k_tab_t, k_tab_k):
    """One CN step for 1D heat diffusion with temperature-dependent k(T).

    Line-faithful port of crankNicolsonStep1D_kT (MATLAB): lagged
    conductivity evaluated at T^n, half-node values by arithmetic mean,
    adiabatic surface (ghost node), Dirichlet T=tamb at the deepest node.
    """
    nz = t_arr.size
    n = nz - 1
    dz2 = dz * dz

    kv = k_hybrid(t_arr[:n], k_tab_t, k_tab_k)
    k_amb = k_hybrid(np.array([tamb]), k_tab_t, k_tab_k)[0]

    k_half = np.empty(n)
    for i in range(n - 1):
        k_half[i] = 0.5 * (kv[i] + kv[i + 1])
    k_half[n - 1] = 0.5 * (kv[n - 1] + k_amb)   # interface to Dirichlet node

    # Fourier numbers at half-nodes: r_{j+1/2} = k_{j+1/2} * dt / (2*Cl*dz^2)
    rh = k_half * dt / (2.0 * cl * dz2)

    a = np.zeros(n)
    b = np.zeros(n)
    c = np.zeros(n)
    d = np.zeros(n)

    # Surface node (adiabatic: ghost T[-1] = T[1], so r_minus = rh[0])
    rp = rh[0]
    b[0] = 1.0 + 2.0 * rp
    c[0] = -2.0 * rp
    d[0] = (1.0 - 2.0 * rp) * t_arr[0] + 2.0 * rp * t_arr[1]

    # Interior nodes
    for i in range(1, n - 1):
        rm = rh[i - 1]
        rp = rh[i]
        a[i] = -rm
        b[i] = 1.0 + rm + rp
        c[i] = -rp
        d[i] = rm * t_arr[i - 1] + (1.0 - rm - rp) * t_arr[i] + rp * t_arr[i + 1]

    # Node adjacent to the Dirichlet boundary
    rm = rh[n - 2]
    rp = rh[n - 1]
    a[n - 1] = -rm
    b[n - 1] = 1.0 + rm + rp
    d[n - 1] = rm * t_arr[n - 2] + (1.0 - rm - rp) * t_arr[n - 1] \
        + rp * tamb + rp * tamb

    # Thomas algorithm
    for i in range(1, n):
        m = a[i] / b[i - 1]
        b[i] = b[i] - m * c[i - 1]
        d[i] = d[i] - m * d[i - 1]

    t_new = t_arr.copy()
    t_new[n - 1] = d[n - 1] / b[n - 1]
    for i in range(n - 2, -1, -1):
        t_new[i] = (d[i] - c[i] * t_new[i + 1]) / b[i]
    t_new[nz - 1] = tamb
    return t_new


@njit(cache=True)
def cn_coast_kt(t_arr, coast_gap, n_diff, dz, tamb, cl, k_tab_t, k_tab_k,
                t_fine_end, sample_interval):
    """Inter-pulse diffusion coast with k(T) CN steps plus surface sampling.

    Mirrors the Phase 2 loop of the depth solver (MATLAB), including the
    sample-collection rule (di % sample_interval == 0 or di == n_diff).
    """
    dt_diff = coast_gap / n_diff

    n_samples = 0
    for di in range(1, n_diff + 1):
        if di % sample_interval == 0 or di == n_diff:
            n_samples += 1
    c_t = np.empty(n_samples)
    c_tl = np.empty(n_samples)

    t_cur = t_arr.copy()
    j = 0
    for di in range(1, n_diff + 1):
        t_cur = crank_nicolson_step_kt(t_cur, dt_diff, dz, tamb, cl, k_tab_t, k_tab_k)
        if di % sample_interval == 0 or di == n_diff:
            c_t[j] = t_fine_end + di * dt_diff
            c_tl[j] = t_cur[0]
            j += 1
    return t_cur, c_t, c_tl


@njit(cache=True)
def ttm_1d_rhs(t, y, nz, dz, gamma, cl, g_ep, kl,
               k_tab_t, k_tab_k, depth_abs_profile,
               n_pulses, trep, pulse_offset, code, tau, eabs_areal):
    """RHS of the coupled 1D TTM PDEs (method of lines).

    Line-faithful port of ttm1dRHS (Depth_Profile_Solver.m):
      Ce(Te)*dTe/dt = d/dz[ke*dTe/dz] - G*(Te-Tl) + S(z,t)
      Cl   *dTl/dt = kl*d2Tl/dz2      + G*(Te-Tl)
    with ke = max(k_hybrid(Tl)-kl, 1) * max(Te,1)/max(Tl,1) and adiabatic
    boundaries at both ends of the fine grid.
    """
    dz2 = dz * dz
    te = y[:nz]
    tl = y[nz:]

    ce = gamma * np.maximum(te, 1.0)

    ke0_local = np.maximum(k_hybrid(tl, k_tab_t, k_tab_k) - kl, 1.0)
    ke = ke0_local * np.maximum(te, 1.0) / np.maximum(tl, 1.0)

    # Electron diffusion: div(ke * grad(Te)), half-node conductivities
    ke_half = 0.5 * (ke[: nz - 1] + ke[1:])
    flux_e = ke_half * (te[1:] - te[: nz - 1]) / dz
    div_ke = np.empty(nz)
    div_ke[0] = flux_e[0] / dz
    div_ke[1: nz - 1] = (flux_e[1:] - flux_e[: nz - 2]) / dz
    div_ke[nz - 1] = -flux_e[nz - 2] / dz

    # Lattice diffusion: kl * d2Tl/dz2 with adiabatic ends
    div_kl = np.empty(nz)
    div_kl[0] = kl * (tl[1] - tl[0]) / dz2
    div_kl[1: nz - 1] = kl * (tl[2:] - 2.0 * tl[1: nz - 1] + tl[: nz - 2]) / dz2
    div_kl[nz - 1] = kl * (tl[nz - 2] - tl[nz - 1]) / dz2

    # Laser source (Beer-Lambert)
    s_t = eabs_areal * source_temporal(t, n_pulses, trep, pulse_offset, code, tau)
    s_z = s_t * depth_abs_profile

    coupling = g_ep * (te - tl)

    dydt = np.empty(2 * nz)
    dydt[:nz] = (div_ke - coupling + s_z) / ce
    dydt[nz:] = (div_kl + coupling) / cl
    return dydt


@njit(cache=True)
def crank_nicolson_step_const(t_arr, r, tamb):
    """One Crank-Nicolson step for 1D heat diffusion with constant diffusivity.

    Line-faithful port of crankNicolsonStep (Surface_Point_Solver.m).
    BCs: adiabatic at z=0 (ghost node), Dirichlet T=tamb at the deepest node.
    r = alpha*dt/dz^2 (Fourier mesh number). Thomas tridiagonal solve.
    """
    nz = t_arr.size
    n = nz - 1  # solve for nodes 0..nz-2 (0-based); last node fixed at tamb

    a = np.zeros(n)
    b = np.zeros(n)
    c = np.zeros(n)
    d = np.zeros(n)

    # Interior nodes (0-based i = 1 .. n-2)
    for i in range(1, n - 1):
        a[i] = -r / 2.0
        b[i] = 1.0 + r
        c[i] = -r / 2.0
        d[i] = (r / 2.0) * t_arr[i - 1] + (1.0 - r) * t_arr[i] + (r / 2.0) * t_arr[i + 1]

    # Surface node (adiabatic: ghost T[-1] = T[1])
    b[0] = 1.0 + r
    c[0] = -r
    d[0] = (1.0 - r) * t_arr[0] + r * t_arr[1]

    # Node adjacent to the Dirichlet boundary (0-based i = n-1)
    a[n - 1] = -r / 2.0
    b[n - 1] = 1.0 + r
    d[n - 1] = (r / 2.0) * t_arr[n - 2] + (1.0 - r) * t_arr[n - 1] \
        + (r / 2.0) * tamb + (r / 2.0) * tamb
    # Two tamb terms: one from the explicit side, one from the implicit side.

    # Thomas algorithm (forward sweep)
    for i in range(1, n):
        m = a[i] / b[i - 1]
        b[i] = b[i] - m * c[i - 1]
        d[i] = d[i] - m * d[i - 1]

    # Back substitution
    t_new = t_arr.copy()
    t_new[n - 1] = d[n - 1] / b[n - 1]
    for i in range(n - 2, -1, -1):
        t_new[i] = (d[i] - c[i] * t_new[i + 1]) / b[i]
    t_new[nz - 1] = tamb  # enforce Dirichlet
    return t_new


@njit(cache=True)
def crank_nicolson_radial_step_kt(t_arr, dt, dr, tamb, cl, k_tab_t, k_tab_k):
    """One CN step for radial (cylindrical) heat diffusion with k(T).

    Line-faithful port of crankNicolsonRadialStep_kT (Radial_Profile_Solver.m):
      dT/dt = (1/r) d/dr( r k(T) dT/dr ) / Cl
    with lagged conductivity at T^n, symmetry (dT/dr = 0) at r = 0 handled via
    L'Hopital (factor 4 on the centre node), and Dirichlet T = tamb at r = rMax.
    """
    nr = t_arr.size
    n = nr - 1
    dr2 = dr * dr

    kv = k_hybrid(t_arr[:n], k_tab_t, k_tab_k)
    k_amb = k_hybrid(np.array([tamb]), k_tab_t, k_tab_k)[0]

    k_half = np.empty(n)
    for i in range(n - 1):
        k_half[i] = 0.5 * (kv[i] + kv[i + 1])
    k_half[n - 1] = 0.5 * (kv[n - 1] + k_amb)

    fh = k_half * dt / (2.0 * cl * dr2)

    a = np.zeros(n)
    b = np.zeros(n)
    c = np.zeros(n)
    d = np.zeros(n)

    # Centre node (r = 0): L'Hopital gives 2 * d2T/dr2
    fp = fh[0]
    b[0] = 1.0 + 4.0 * fp
    c[0] = -4.0 * fp
    d[0] = (1.0 - 4.0 * fp) * t_arr[0] + 4.0 * fp * t_arr[1]

    # Interior nodes (0-based i is also the physical radial index j)
    for i in range(1, n - 1):
        rp_w = (i + 0.5) / i
        rm_w = (i - 0.5) / i
        fp_i = fh[i] * rp_w
        fm_i = fh[i - 1] * rm_w
        a[i] = -fm_i
        b[i] = 1.0 + fm_i + fp_i
        c[i] = -fp_i
        d[i] = fm_i * t_arr[i - 1] + (1.0 - fm_i - fp_i) * t_arr[i] + fp_i * t_arr[i + 1]

    # Node adjacent to the Dirichlet boundary
    j_last = n - 1
    rp_w = (j_last + 0.5) / j_last
    rm_w = (j_last - 0.5) / j_last
    fp_n = fh[n - 1] * rp_w
    fm_n = fh[n - 2] * rm_w
    a[n - 1] = -fm_n
    b[n - 1] = 1.0 + fm_n + fp_n
    d[n - 1] = fm_n * t_arr[n - 2] + (1.0 - fm_n - fp_n) * t_arr[n - 1] \
        + fp_n * tamb + fp_n * tamb

    # Thomas algorithm
    for i in range(1, n):
        m = a[i] / b[i - 1]
        b[i] = b[i] - m * c[i - 1]
        d[i] = d[i] - m * d[i - 1]

    t_new = t_arr.copy()
    t_new[n - 1] = d[n - 1] / b[n - 1]
    for i in range(n - 2, -1, -1):
        t_new[i] = (d[i] - c[i] * t_new[i + 1]) / b[i]
    t_new[nr - 1] = tamb
    return t_new


@njit(cache=True)
def radial_coast_kt(t_arr, n_steps, dt, dr, tamb, cl, k_tab_t, k_tab_k):
    """n_steps radial CN k(T) steps (the per-pulse radial coast loop)."""
    t_cur = t_arr.copy()
    for _ in range(n_steps):
        t_cur = crank_nicolson_radial_step_kt(t_cur, dt, dr, tamb, cl, k_tab_t, k_tab_k)
    return t_cur


@njit(cache=True)
def cn_depth_multi_kt(tz_all, active, n_steps, dt, dz, tamb, cl,
                      k_tab_t, k_tab_k, t_fine_end, sample_interval):
    """Depth-CN coast applied to every active radial node's depth column.

    Port of the 'independent'-mode Phase 2 loop of Radial_Profile_Solver.m:
    per CN step, every active column advances (inactive columns — negligible
    fluence — are skipped exactly as in MATLAB), and the centre column's
    surface temperature is sampled on the usual (di % sample_interval == 0
    or di == n_steps) rule. tz_all is modified in place; returns the sampled
    (times, centre surface T) arrays.
    """
    n_samples = 0
    for di in range(1, n_steps + 1):
        if di % sample_interval == 0 or di == n_steps:
            n_samples += 1
    c_t = np.empty(n_samples)
    c_tl = np.empty(n_samples)

    nr = tz_all.shape[1]
    j = 0
    for di in range(1, n_steps + 1):
        for ri in range(nr):
            if not active[ri]:
                continue
            tz_all[:, ri] = crank_nicolson_step_kt(
                tz_all[:, ri].copy(), dt, dz, tamb, cl, k_tab_t, k_tab_k)
        if di % sample_interval == 0 or di == n_steps:
            c_t[j] = t_fine_end + di * dt
            c_tl[j] = tz_all[0, 0]
            j += 1
    return c_t, c_tl


@njit(cache=True)
def rk4_single_pulse_response(t0, gamma, g_ep, cl, tau, pulse_offset, code, eabs_vol):
    """Single-pulse 0D RK4 response used by the scanning-beam solver.

    Line-faithful port of the single-pulse while-loop in
    Scanning_Beam_Solver.m: fixed fine resolution inside +/- 6*tau of the
    pulse centre, stability-limited dt elsewhere, run until the relative
    electron-lattice difference converges below 1e-6 (or t reaches
    pulse_offset + 50*tau). Returns the end-state (Te, Tl).
    """
    te = t0
    tl = t0
    tc = 0.0
    t_end = pulse_offset + 50.0 * tau
    dt_pulse = tau / 40.0
    past_pulse = False
    n_pulses = 1
    trep = 1.0  # irrelevant for a single pulse (cutoff keeps only pulse 0)

    while tc < t_end:
        ce_now = gamma * max(te, 1.0)
        dt_stab = 0.2 * ce_now / g_ep
        if abs(tc - pulse_offset) < 6.0 * tau:
            dt = min(dt_stab, dt_pulse)
        else:
            dt = dt_stab
            past_pulse = True
        dt = max(dt, 1e-17)

        k1e, k1l, _ = _ttm_derivs_0d(tc, te, tl, gamma, g_ep, cl,
                                     n_pulses, trep, pulse_offset, code, tau, eabs_vol)
        k2e, k2l, _ = _ttm_derivs_0d(tc + dt / 2, te + dt / 2 * k1e, tl + dt / 2 * k1l,
                                     gamma, g_ep, cl,
                                     n_pulses, trep, pulse_offset, code, tau, eabs_vol)
        k3e, k3l, _ = _ttm_derivs_0d(tc + dt / 2, te + dt / 2 * k2e, tl + dt / 2 * k2l,
                                     gamma, g_ep, cl,
                                     n_pulses, trep, pulse_offset, code, tau, eabs_vol)
        k4e, k4l, _ = _ttm_derivs_0d(tc + dt, te + dt * k3e, tl + dt * k3l,
                                     gamma, g_ep, cl,
                                     n_pulses, trep, pulse_offset, code, tau, eabs_vol)
        te = max(te + (dt / 6.0) * (k1e + 2.0 * k2e + 2.0 * k3e + k4e), 1.0)
        tl = max(tl + (dt / 6.0) * (k1l + 2.0 * k2l + 2.0 * k3l + k4l), 1.0)
        tc = tc + dt
        if past_pulse and abs(te - tl) / max(tl, 1.0) < 1e-6:
            break
    return te, tl


@njit(cache=True)
def _thomas_prefactor(a, b, c):
    """Forward-eliminate a constant tridiagonal system once.

    Returns (m, bp): the row multipliers and modified diagonal, so repeated
    solves only sweep the right-hand side. Arithmetic is identical to running
    the full Thomas algorithm each call.
    """
    n = b.size
    m = np.zeros(n)
    bp = b.copy()
    for i in range(1, n):
        m[i] = a[i] / bp[i - 1]
        bp[i] = b[i] - m[i] * c[i - 1]
    return m, bp


@njit(cache=True)
def _thomas_solve_prefactored(m, bp, c, d, x):
    """Solve with a prefactored tridiagonal system (in-place result in x)."""
    n = bp.size
    dp = d  # forward sweep in place
    for i in range(1, n):
        dp[i] = dp[i] - m[i] * dp[i - 1]
    x[n - 1] = dp[n - 1] / bp[n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = (dp[i] - c[i] * x[i + 1]) / bp[i]


@njit(cache=True)
def scanning_chunk(np_start, np_end,
                   tsurf, tpeak, tz, peak_hist,
                   x_grid, gy_gauss, inv2w2, v_scan, trep, dteq_single, t0,
                   depth_is_exp, exp_decay_z, box_mask_z,
                   n_cn, ndiff, r_diff,
                   nadi, fxdt, fydt):
    """Pulses np_start..np_end-1 (0-based) of the scanning-beam main loop.

    Line-faithful port of the vectorized MATLAB loop: Gaussian deposit by
    outer product, peak-map update, depth CN coast with survival scaling,
    then NadiPerGap ADI lateral-diffusion steps with Dirichlet T0 borders.
    All state arrays (tsurf, tpeak, tz, peak_hist) are updated in place.
    """
    ny, nx = tsurf.shape

    # --- Prefactored depth-CN system (constant r_diff; solve for nodes 0..n_cn-1)
    a_d = np.zeros(n_cn)
    b_d = np.full(n_cn, 1.0 + r_diff)
    c_d = np.zeros(n_cn)
    c_d[0] = -r_diff                       # Neumann (adiabatic) surface BC
    for i in range(1, n_cn - 1):
        a_d[i] = -r_diff / 2.0
        c_d[i] = -r_diff / 2.0
    a_d[n_cn - 1] = -r_diff / 2.0
    m_d, bp_d = _thomas_prefactor(a_d, b_d, c_d)
    d_d = np.empty(n_cn)

    # --- Prefactored ADI systems (interior unknowns only)
    nx_int = nx - 2
    ny_int = ny - 2
    a_x = np.full(nx_int, -fxdt / 2.0)
    b_x = np.full(nx_int, 1.0 + fxdt)
    c_x = np.full(nx_int, -fxdt / 2.0)
    a_x[0] = 0.0
    c_x[nx_int - 1] = 0.0
    m_x, bp_x = _thomas_prefactor(a_x, b_x, c_x)

    a_y = np.full(ny_int, -fydt / 2.0)
    b_y = np.full(ny_int, 1.0 + fydt)
    c_y = np.full(ny_int, -fydt / 2.0)
    a_y[0] = 0.0
    c_y[ny_int - 1] = 0.0
    m_y, bp_y = _thomas_prefactor(a_y, b_y, c_y)

    bx_adi = (fxdt / 2.0) * t0
    by_adi = (fydt / 2.0) * t0

    rhs_row = np.empty(nx_int)
    sol_row = np.empty(nx_int)
    rhs_col = np.empty(ny_int)
    sol_col = np.empty(ny_int)
    thalf = np.empty((ny, nx))

    for np_i in range(np_start, np_end):
        # --- Gaussian fluence deposit (outer product) ---
        x_laser = v_scan * np_i * trep
        peak_surf = -1.0e300
        for ix in range(nx):
            gx = np.exp(-inv2w2 * (x_grid[ix] - x_laser) ** 2)
            for iy in range(ny):
                v = tsurf[iy, ix] + dteq_single * gy_gauss[iy] * gx
                tsurf[iy, ix] = v
                tpeak[iy, ix] = max(tpeak[iy, ix], v)
                peak_surf = max(peak_surf, v)
        peak_hist[np_i] = peak_surf

        # --- Depth CN coast with survival scaling ---
        if depth_is_exp:
            delta = peak_surf - tz[0]
            for iz in range(tz.size):
                tz[iz] = tz[iz] + delta * exp_decay_z[iz]
        else:
            for iz in range(tz.size):
                if box_mask_z[iz]:
                    tz[iz] = peak_surf
        tsurf_max_before = tz[0]

        for _ in range(ndiff):
            # d = B * Tz_int + bvec (surface Neumann row, Dirichlet bottom)
            d_d[0] = (1.0 - r_diff) * tz[0] + r_diff * tz[1]
            for i in range(1, n_cn - 1):
                d_d[i] = (r_diff / 2.0) * tz[i - 1] + (1.0 - r_diff) * tz[i] \
                    + (r_diff / 2.0) * tz[i + 1]
            d_d[n_cn - 1] = (r_diff / 2.0) * tz[n_cn - 2] \
                + (1.0 - r_diff) * tz[n_cn - 1] + r_diff * t0
            _thomas_solve_prefactored(m_d, bp_d, c_d, d_d, tz[:n_cn])
        tz[tz.size - 1] = t0

        if (tsurf_max_before - t0) > 1e-10:
            survival = (tz[0] - t0) / (tsurf_max_before - t0)
            survival = max(survival, 0.0)
        else:
            survival = 1.0
        for ix in range(nx):
            for iy in range(ny):
                tsurf[iy, ix] = t0 + (tsurf[iy, ix] - t0) * survival

        # --- ADI lateral diffusion ---
        for _ in range(nadi):
            # X-sweep: implicit in x, explicit in y
            for iy in range(1, ny - 1):
                for ix in range(1, nx - 1):
                    rhs_row[ix - 1] = tsurf[iy, ix] + (fydt / 2.0) * (
                        tsurf[iy - 1, ix] - 2.0 * tsurf[iy, ix] + tsurf[iy + 1, ix])
                rhs_row[0] += bx_adi
                rhs_row[nx_int - 1] += bx_adi
                _thomas_solve_prefactored(m_x, bp_x, c_x, rhs_row, sol_row)
                for ix in range(1, nx - 1):
                    thalf[iy, ix] = sol_row[ix - 1]
            for ix in range(nx):
                thalf[0, ix] = t0
                thalf[ny - 1, ix] = t0
            for iy in range(ny):
                thalf[iy, 0] = t0
                thalf[iy, nx - 1] = t0

            # Y-sweep: implicit in y, explicit in x
            for ix in range(1, nx - 1):
                for iy in range(1, ny - 1):
                    rhs_col[iy - 1] = thalf[iy, ix] + (fxdt / 2.0) * (
                        thalf[iy, ix - 1] - 2.0 * thalf[iy, ix] + thalf[iy, ix + 1])
                rhs_col[0] += by_adi
                rhs_col[ny_int - 1] += by_adi
                _thomas_solve_prefactored(m_y, bp_y, c_y, rhs_col, sol_col)
                for iy in range(1, ny - 1):
                    tsurf[iy, ix] = sol_col[iy - 1]
            for ix in range(nx):
                tsurf[0, ix] = t0
                tsurf[ny - 1, ix] = t0
            for iy in range(ny):
                tsurf[iy, 0] = t0
                tsurf[iy, nx - 1] = t0


@njit(cache=True)
def cn_coast_const(t_arr, coast_gap, n_diff, alpha, dz, tamb, t_fine_end, sample_interval):
    """Phase 2 of the 0D model: n_diff CN steps over coast_gap seconds.

    Runs the whole inter-pulse diffusion coast inside one jitted call and
    collects the sampled surface-temperature trace exactly like the MATLAB
    loop (sample at di % sample_interval == 0 or di == n_diff, 1-based di).

    Returns (t_arr_final, coast_times, coast_surface_T).
    """
    dt_diff = coast_gap / n_diff
    r = alpha * dt_diff / (dz * dz)

    n_samples = 0
    for di in range(1, n_diff + 1):
        if di % sample_interval == 0 or di == n_diff:
            n_samples += 1
    c_t = np.empty(n_samples)
    c_tl = np.empty(n_samples)

    t_cur = t_arr.copy()
    j = 0
    for di in range(1, n_diff + 1):
        t_cur = crank_nicolson_step_const(t_cur, r, tamb)
        if di % sample_interval == 0 or di == n_diff:
            c_t[j] = t_fine_end + di * dt_diff
            c_tl[j] = t_cur[0]
            j += 1
    return t_cur, c_t, c_tl
